version: '3.8'

services:
  yii2:
    build:
      context: .
      dockerfile: Dockerfile
    image: tohidazure/yii2-app:latest
    restart: always
    environment:
      - YII_ENV=prod
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3 